### PR TITLE
Update tokio-cron-scheduler to version 0.9.4 to fix build error.

### PR DESCRIPTION
**Pull request by opi-smccoole**
Fix for #86 compilation errors when trying to build/install via cargo or locally.

Build would error out with:

```
error[E0308]: mismatched types
   --> /Users/mccoole/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-cron-scheduler-0.7.6/src/job/mod.rs:346:41
    |
346 |                       .checked_add_signed(time::Duration::seconds(
    |  ______________________------------------_^
    | |                      |
    | |                      arguments to this method are incorrect
347 | |                         instant.duration_since(Instant::now()).as_secs() as i64,
348 | |                     ))
    | |_____________________^ expected `chrono::Duration`, found `time::Duration`
    |
    = note: `time::Duration` and `chrono::Duration` have similar names, but are actually distinct types
note: `time::Duration` is defined in crate `time`
   --> /Users/mccoole/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.1.45/src/duration.rs:45:1
    |
45  | pub struct Duration {
    | ^^^^^^^^^^^^^^^^^^^
note: `chrono::Duration` is defined in crate `chrono`
   --> /Users/mccoole/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chrono-0.4.31/src/duration.rs:55:1
    |
55  | pub struct Duration {
    | ^^^^^^^^^^^^^^^^^^^
note: method defined here
   --> /Users/mccoole/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chrono-0.4.31/src/datetime/mod.rs:377:12
    |
377 |     pub fn checked_add_signed(self, rhs: OldDuration) -> Option<DateTime<Tz>> {
    |            ^^^^^^^^^^^^^^^^^^

```

Updated tokio-chron-scheduler to version 0.9.4.
Change implicit awaits in scheduling to explicit.

I'm not a rust developer by any stretch of the imagination so this may be off base but seems to be building and working for me locally.

### CODE REVIEW

**Comment by opi-smccoole** [comment]
Hmm, not really sure why the inconsistent test results.  Some are packing errors and others are related to the animation calls which I don't *think* I should have messed up.  Additionally `cargo test -p divoom --doc` passes locally as does `cargo test --workspace` but I am on a Mac.

**Comment by r12f** [comment]
hi Steve, thanks a lot for the contribution! I believe the windows failures are caused by the cert update and I have got them fixed by updating the build pipeline.

The image files are caused by the image lib updates. However, the generated image looks the same, so it should be some internal format gets updated.

image

I removed the cargo.lock file on windows, and i can repo the failure on windows too.

image

Do you mind to help remove the cargo.lock file on your machine, then use the following commands to regenerate the test base data and submit another iteration? I guess the failures will be gone after the change.

```bash
export DIVOOM_API_GENERATE_TEST_DATA=1
just test
```

**Comment by opi-smccoole** [comment]
Thanks for taking a look!  I am on an M1 MacBook and when I run `just test` it is complaining about being on an unsupported platform unfortunately.  I am not familiar with the rust ecosystem.  Is there a way to update the justfile to allow it to work on the M1?

**Comment by opi-smccoole** [comment]
I got my environment to run the `justfile` with an addition to it but when I do the export and run `just test` nothing seems to update beyond the `justfile` change I made myself?

**Comment by opi-smccoole** [comment]
Well, I have to admit, I am stumped.  I've tried every variant of running the tests and the image files are not updating.  Any idea as to what might be going on?

**Comment by r12f** [comment]
ouch, not sure if this is anything special for M1, but I don't have any M1 board to verify...

let me see if I can maybe fork your branch and get it working.

**Comment by r12f** [comment]
Ok, updated now. need to be afk for a while and let's see how it goes. :D

**Comment by r12f** [comment]
Looks like the linux build is failing because of some sort of OpenSSL problem. It could cause some glibc heap issue like below:

```
running 5 tests
malloc(): unaligned tcache chunk detected
Aborted
```

image

**Comment by r12f** [comment]
switched to openssl-sys and solved the heap corruption issue locally. let's see how it looks with ci.

**Comment by r12f** [comment]
somehow this PR action cannot pickup the right environment variables, so manually kicked off one here: https://riff.visualstudio.com/divoom/_build/results?buildId=734&view=results.

**Comment by r12f** [comment]
looks like I will need to spend some more time tomorrow to see how to get the openssl issue fixed. maybe using cross.toml or make reqwest use rustls... but it will take time now.

**Comment by opi-smccoole** [comment]
Thanks for all of the assistance on this!  Sorry that it is consuming so much extra time.

**Comment by r12f** [comment]
thank you for bringing this issue up and helping doing the change too! will continue to look into this one late today. openssl in rust is always fun, especially for cross build :D

**Comment by r12f** [comment]
got stuck for long time because of some libc not found error... it turns out i have to delete everything in target folder before doing the cross build, lol.

switched to rustls and see if it works. local build works fine, not sure if this can safely apply to all platforms and passes tests

**Comment by r12f** [comment]
ok, looks like it works! the windows failure is still the cert issue, not sure why CI cannot pick up the new environment variables... but I manually kicked off one here to double confirm: https://riff.visualstudio.com/divoom/_build/results?buildId=737&view=results.

**Comment by r12f** [comment]
ci is passed! https://riff.visualstudio.com/divoom/_build/results?buildId=737&view=results

@opi-smccoole, is there any additional thing you like to add? if not, i am going to merge the change. :D

**Comment by BreadYogurt** [comment]
Can this be merged now? I think a week is long enough to wait for approval.

**Comment by r12f** [comment]
@BreadYogurt , I am not waiting for anything else, but checking if anything else is needed from the original author.

But since I am not seeing any new update from @opi-smccoole , I am going to assume he it good with this change now.

**Comment by r12f** [comment]
Hi @opi-smccoole , this change is merged now. If anything else is needed, please feel free to submit them as a different PR. 

Thanks a lot for the contribution!

**Comment by opi-smccoole** [comment]
> Hi @opi-smccoole , this change is merged now. If anything else is needed, please feel free to submit them as a different PR.
> 
> Thanks a lot for the contribution!

Sorry, I started a new job a few weeks back and I hadn't had a chance to check back on this.  Thanks for getting it the rest of the way complete and passing!

**Comment by AdrieanKhisbe** [comment]
Hi :)

Would it be possible to release a new version?

I'm still facing the #86 trying to install with `cargo install divoom-cli`, (`error: could not compile `tokio-cron-scheduler` (lib) due to 4 previous errors`)
and the [crates.io version](https://crates.io/crates/divoom-cli) is still prior this PR.



Huge thanks in advance :)

**Pull request merged**
